4.1 TASK 1


In [ ]:
def length_conversion(value: float, unit: str) -> float:
    if unit == 'm':
        return value * 3.28084  # meters to feet
    elif unit == 'ft':
        return value / 3.28084  # feet to meters
    else:
        raise ValueError('Unsupported length unit.')

def weight_conversion(value: float, unit: str) -> float:
    if unit == 'kg':
        return value * 2.20462  # kilograms to pounds
    elif unit == 'lbs':
        return value / 2.20462  # pounds to kilograms
    else:
        raise ValueError('Unsupported weight unit.')

def volume_conversion(value: float, unit: str) -> float:
    if unit == 'L':
        return value * 0.264172  # liters to gallons
    elif unit == 'gal':
        return value / 0.264172  # gallons to liters
    else:
        raise ValueError('Unsupported volume unit.')


def main():
    try:
        conversion_type = input('Choose conversion type (length, weight, volume): ').strip().lower()
        value = float(input('Enter the value to convert: '))

        if conversion_type == 'length':
            unit = input('Enter the unit (m or ft): ').strip().lower()
            result = length_conversion(value, unit)
            print(f'Converted value: {result}')
        elif conversion_type == 'weight':
            unit = input('Enter the unit (kg or lbs): ').strip().lower()
            result = weight_conversion(value, unit)
            print(f'Converted value: {result}')
        elif conversion_type == 'volume':
            unit = input('Enter the unit (L or gal): ').strip().lower()
            result = volume_conversion(value, unit)
            print(f'Converted value: {result}')
        else:
            print('Invalid conversion type.')
    except ValueError as e:
        print(f'Error: {e}')

if __name__ == '__main__':
    main()

Choose conversion type (length, weight, volume): weight
Enter the value to convert: 5
Enter the unit (kg or lbs): kg
Converted value: 11.0231


4.1 TASK 2

In [ ]:
def calculate_sum(numbers: list) -> float:
    return sum(numbers)

def calculate_average(numbers: list) -> float:
    if not numbers:
        raise ValueError('Cannot calculate average of an empty list.')
    return sum(numbers) / len(numbers)

def calculate_maximum(numbers: list) -> float:
    return max(numbers)

def calculate_minimum(numbers: list) -> float:
    return min(numbers)


def main():
    try:
        operation = input('Choose operation (sum, average, maximum, minimum): ').strip().lower()
        numbers_input = input('Enter a list of numbers separated by spaces: ').strip()
        numbers = [float(num) for num in numbers_input.split()]
        if not numbers:
            raise ValueError('The list of numbers cannot be empty.')

        if operation == 'sum':
            result = calculate_sum(numbers)
        elif operation == 'average':
            result = calculate_average(numbers)
        elif operation == 'maximum':
            result = calculate_maximum(numbers)
        elif operation == 'minimum':
            result = calculate_minimum(numbers)
        else:
            print('Invalid operation. Please choose from sum, average, maximum, minimum.')
            return
        print(f'Result: {result}')
    except ValueError as e:
        print(f'Error: {e}')

if __name__ == '__main__':
    main()

Choose operation (sum, average, maximum, minimum): sum
Enter a list of numbers separated by spaces: 1 2 3
Result: 6.0


4.2


In [ ]:
#Extract Every Other Element:
def extract_every_other(lst: list) -> list:
    return lst[::2]
#Slice a Sublist:
def get_sublist(lst: list, start: int, end: int) -> list:
    return lst[start:end+1]
#Reverse a List Using Slicing:
def reverse_list(lst: list) -> list:
    return lst[::-1]
#Remove the First and Last Elements:
def remove_first_last(lst: list) -> list:
    return lst[1:-1]
#Get the First n Elements:
def get_first_n(lst: list, n: int) -> list:
    return lst[:n]
#Extract Elements from the End:
def get_last_n(lst: list, n: int) -> list:
    return lst[-n:]
#Extract Elements in Reverse Order:
def reverse_skip(lst: list) -> list:
    return lst[-2::-2]

# Example usage
if __name__ == '__main__':
    lst = [1, 2, 3, 4, 5, 6]
    print("Extract Every Other Element:", extract_every_other(lst))
    print("Slice a Sublist (2 to 4):", get_sublist(lst, 2, 4))
    print("Reverse a List:", reverse_list(lst))
    print("Remove First and Last Elements:", remove_first_last(lst))
    print("Get First 3 Elements:", get_first_n(lst, 3))
    print("Get Last 2 Elements:", get_last_n(lst, 2))
    print("Extract Elements in Reverse Order:", reverse_skip(lst))


Extract Every Other Element: [1, 3, 5]
Slice a Sublist (2 to 4): [3, 4, 5]
Reverse a List: [6, 5, 4, 3, 2, 1]
Remove First and Last Elements: [2, 3, 4, 5]
Get First 3 Elements: [1, 2, 3]
Get Last 2 Elements: [5, 6]
Extract Elements in Reverse Order: [5, 3, 1]


4.3

In [ ]:
from typing import Any, List

def flatten(lst: List) -> List:
    flat_list = []
    for item in lst:
        if isinstance(item, list):
            flat_list.extend(flatten(item))
        else:
            flat_list.append(item)
    return flat_list

def access_nested_element(lst: List, indices: List[int]) -> Any:
    element = lst
    for index in indices:
        element = element[index]
    return element

def sum_nested(lst: List) -> float:
    return sum(flatten(lst))

def remove_element(lst: List, elem: Any) -> List:
    if isinstance(lst, list):
        return [remove_element(sub, elem) for sub in lst if sub != elem]
    return lst

def find_max(lst: List) -> Any:
    return max(flatten(lst))

def count_occurrences(lst: List, elem: Any) -> int:
    return flatten(lst).count(elem)

def deep_flatten(lst: List) -> List:
    return flatten(lst)

def average_nested(lst: List) -> float:
    flat_list = flatten(lst)
    return sum(flat_list) / len(flat_list) if flat_list else 0

# Example usage
if __name__ == '__main__':
    nested_list = [[1, 2], [3, [4, 5]], 6]
    print("Flatten a Nested List:", flatten(nested_list))
    print("Access Nested Element:", access_nested_element([[1, 2, 3], [4, 5, 6], [7, 8, 9]], [1, 2]))
    print("Sum of All Elements:", sum_nested(nested_list))
    print("Remove Specific Element:", remove_element([[1, 2], [3, 2], [4, 5]], 2))
    print("Find Maximum Element:", find_max(nested_list))
    print("Count Occurrences:", count_occurrences([[1, 2], [2, 3], [2, 4]], 2))
    print("Deep Flatten a List of Lists of Lists:", deep_flatten([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]))
    print("Nested List Average:", average_nested([[1, 2], [3, 4], [5, 6]]))

Flatten a Nested List: [1, 2, 3, 4, 5, 6]
Access Nested Element: 6
Sum of All Elements: 21
Remove Specific Element: [[1], [3], [4, 5]]
Find Maximum Element: 6
Count Occurrences: 3
Deep Flatten a List of Lists of Lists: [1, 2, 3, 4, 5, 6, 7, 8]
Nested List Average: 3.5


10.1

In [ ]:
import numpy as np

# 1. Initialize an empty array with size 2X2.
empty_array = np.empty((2, 2))
print("Empty Array (2x2):\n", empty_array)

# 2. Initialize an all-one array with size 4X2.
ones_array = np.ones((4, 2))
print("\nAll Ones Array (4x2):\n", ones_array)

# 3. Return a new array of given shape and type, filled with a fill value.
# Example: Fill value = 7, shape = (3, 3)
filled_array = np.full((3, 3), 7)
print("\nArray filled with 7 (3x3):\n", filled_array)

# 4. Return a new array of zeros with same shape and type as a given array.
given_array = np.array([[5, 6], [7, 8]])
zeros_like_array = np.zeros_like(given_array)
print("\nArray of Zeros with same shape as given array:\n", zeros_like_array)

# 5. Return a new array of ones with same shape and type as a given array.
ones_like_array = np.ones_like(given_array)
print("\nArray of Ones with same shape as given array:\n", ones_like_array)

# 6. Convert an existing list to a numpy array.
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("\nConverted list to Numpy Array:\n", numpy_array)

Empty Array (2x2):
 [[1.65059684e-316 0.00000000e+000]
 [4.22797985e-307 1.00813461e-109]]

All Ones Array (4x2):
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Array filled with 7 (3x3):
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

Array of Zeros with same shape as given array:
 [[0 0]
 [0 0]]

Array of Ones with same shape as given array:
 [[1 1]
 [1 1]]

Converted list to Numpy Array:
 [1 2 3 4]


In [ ]:
import numpy as np

# 1. Create an array with values ranging from 10 to 49.
array_10_to_49 = np.arange(10, 50)
print("Array with values from 10 to 49:\n", array_10_to_49)

# 2. Create a 3x3 matrix with values ranging from 0 to 8.
matrix_0_to_8 = np.arange(9).reshape(3, 3)
print("\n3x3 Matrix with values from 0 to 8:\n", matrix_0_to_8)

# 3. Create a 3x3 identity matrix.
identity_matrix = np.eye(3)
print("\n3x3 Identity Matrix:\n", identity_matrix)

# 4. Create a random array of size 30 and find the mean of the array.
random_array = np.random.random(30)
mean_value = random_array.mean()
print("\nRandom Array of size 30:\n", random_array)
print("Mean of the array:", mean_value)

# 5. Create a 10x10 array with random values and find the minimum and maximum values.
random_10x10 = np.random.random((10, 10))
min_value = random_10x10.min()
max_value = random_10x10.max()
print("\n10x10 Random Array:\n", random_10x10)
print("Minimum Value:", min_value)
print("Maximum Value:", max_value)

# 6. Create a zero array of size 10 and replace the 5th element with 1.
zero_array = np.zeros(10)
zero_array[4] = 1
print("\nZero Array with 5th element as 1:\n", zero_array)

# 7. Reverse an array arr = [1,2,0,0,4,0].
arr = [1, 2, 0, 0, 4, 0]
reversed_arr = arr[::-1]
print("\nReversed Array:\n", reversed_arr)

# 8. Create a 2D array with 1 on border and 0 inside.
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("\n2D Array with 1 on border and 0 inside:\n", border_array)

# 9. Create an 8x8 matrix and fill it with a checkerboard pattern.
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n8x8 Checkerboard Pattern:\n", checkerboard)

Array with values from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 Matrix with values from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random Array of size 30:
 [0.11098673 0.23277292 0.09615651 0.0794697  0.13088835 0.80956024
 0.32628972 0.00490474 0.54239096 0.16030453 0.1618258  0.81483544
 0.73705398 0.93893601 0.71658125 0.59928376 0.98294086 0.08223269
 0.56355635 0.76418279 0.66938672 0.75629593 0.80513357 0.17385357
 0.76600316 0.91777743 0.95069058 0.49271777 0.68366621 0.3834295 ]
Mean of the array: 0.5151369254821966

10x10 Random Array:
 [[0.36362307 0.37964462 0.00659981 0.45233469 0.11045338 0.67069514
  0.20949806 0.74895202 0.42786851 0.65219206]
 [0.071418   0.84426708 0.94206135 0.36345815 0.83208599 0.34772839
  0.94212548 0.13524223 0.41855654 0.23645702]
 [0.79661566 0.65347605 0.37031438 0.03498109 0.12470136 0.76235

In [ ]:
import numpy as np

# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add the two arrays.
addition = x + y
print("Addition of x and y:\n", addition)

# 2. Subtract the two arrays.
subtraction = x - y
print("\nSubtraction of x and y:\n", subtraction)

# 3. Multiply the array with any integers of your choice (e.g., multiply x by 2).
multiplication = x * 2
print("\nMultiplication of x by 2:\n", multiplication)

# 4. Find the square of each element of the array.
square_x = np.square(x)
print("\nSquare of each element of x:\n", square_x)

# 5. Find the dot product between:
# v and w
dot_v_w = np.dot(v, w)
# x and v
dot_x_v = np.dot(x, v)
# x and y
dot_x_y = np.dot(x, y)
print("\nDot Product between v and w:", dot_v_w)
print("Dot Product between x and v:\n", dot_x_v)
print("Dot Product between x and y:\n", dot_x_y)

# 6. Concatenate x and y along row (axis 0) and Concatenate v and w along column (axis 1).
concat_x_y_row = np.concatenate((x, y), axis=0)
concat_v_w_col = np.concatenate((v.reshape(-1, 1), w.reshape(-1, 1)), axis=1)
print("\nConcatenation of x and y along rows:\n", concat_x_y_row)
print("Concatenation of v and w along columns:\n", concat_v_w_col)

# 7. Concatenate x and v; if you get an error, observe and explain why you got the error.
try:
    concat_x_v = np.concatenate((x, v))
    print("\nConcatenation of x and v:\n", concat_x_v)
except Exception as e:
    print("\nError during concatenation of x and v:", e)

Addition of x and y:
 [[ 6  8]
 [10 13]]

Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]

Multiplication of x by 2:
 [[ 2  4]
 [ 6 10]]

Square of each element of x:
 [[ 1  4]
 [ 9 25]]

Dot Product between v and w: 219
Dot Product between x and v:
 [29 77]
Dot Product between x and y:
 [[19 22]
 [50 58]]

Concatenation of x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenation of v and w along columns:
 [[ 9 11]
 [10 12]]

Error during concatenation of x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


In [ ]:
import numpy as np

# Given arrays
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A * A^(-1) = I (Identity Matrix)
A_inv = np.linalg.inv(A)  # Inverse of A
I = np.eye(2)  # Identity matrix of size 2x2
result_1 = np.dot(A, A_inv)
print("A * A^(-1) =\n", result_1)
print("Identity Matrix:\n", I)

# 2. Prove AB != BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\nAB =\n", AB)
print("BA =\n", BA)

# Check if AB == BA
if np.array_equal(AB, BA):
    print("\nAB is equal to BA")
else:
    print("\nAB is not equal to BA")

# 3. Prove (AB)^T = B^T * A^T
AB_T = np.transpose(AB)
BT_AT = np.dot(np.transpose(B), np.transpose(A))
print("\n(AB)^T =\n", AB_T)
print("B^T * A^T =\n", BT_AT)

# Check if (AB)^T == B^T * A^T
if np.array_equal(AB_T, BT_AT):
    print("\n(AB)^T = B^T * A^T is True")
else:
    print("\n(AB)^T = B^T * A^T is False")

# Solve the linear system using Inverse Method

# Representing the equations in matrix form as AX = B
# The system of equations:
# 2x - 3y + z = -1
# x - y + 2z = -3
# 3x + y - z = 9

# Coefficient matrix A
A_system = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])

# Constant matrix B
B_system = np.array([-1, -3, 9])

# Solving for X using inverse of A
X = np.linalg.inv(A_system).dot(B_system)
print("\nSolution to the linear system (Inverse Method):\n", X)

# Now solve using np.linalg.solve (Alternative to using np.linalg.inv)
X_solved = np.linalg.solve(A_system, B_system)
print("\nSolution using np.linalg.solve:\n", X_solved)

A * A^(-1) =
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Identity Matrix:
 [[1. 0.]
 [0. 1.]]

AB =
 [[23 13]
 [51 29]]
BA =
 [[36 44]
 [13 16]]

AB is not equal to BA

(AB)^T =
 [[23 51]
 [13 29]]
B^T * A^T =
 [[23 51]
 [13 29]]

(AB)^T = B^T * A^T is True

Solution to the linear system (Inverse Method):
 [ 2.  1. -2.]

Solution using np.linalg.solve:
 [ 2.  1. -2.]


10.2

In [ ]:
import numpy as np
import time

# Create lists and arrays for the operations
size = 1000000  # for element-wise operations
matrix_size = 1000  # for matrix multiplication

# 1. Element-wise Addition
# Using Python Lists:
list1 = [i for i in range(size)]
list2 = [i for i in range(size)]

# Measure the time for element-wise addition using Python lists
start_time = time.time()
result_list_add = [list1[i] + list2[i] for i in range(size)]
end_time = time.time()
print("Time taken for element-wise addition using Python lists:", end_time - start_time)

# Using NumPy Arrays:
array1 = np.array(list1)
array2 = np.array(list2)

# Measure the time for element-wise addition using NumPy arrays
start_time = time.time()
result_array_add = array1 + array2
end_time = time.time()
print("Time taken for element-wise addition using NumPy arrays:", end_time - start_time)

# 2. Element-wise Multiplication
# Using Python Lists:
start_time = time.time()
result_list_mul = [list1[i] * list2[i] for i in range(size)]
end_time = time.time()
print("\nTime taken for element-wise multiplication using Python lists:", end_time - start_time)

# Using NumPy Arrays:
start_time = time.time()
result_array_mul = array1 * array2
end_time = time.time()
print("Time taken for element-wise multiplication using NumPy arrays:", end_time - start_time)

# 3. Dot Product
# Using Python Lists:
start_time = time.time()
dot_product_list = sum(list1[i] * list2[i] for i in range(size))
end_time = time.time()
print("\nTime taken for dot product using Python lists:", end_time - start_time)

# Using NumPy Arrays:
start_time = time.time()
dot_product_array = np.dot(array1, array2)
end_time = time.time()
print("Time taken for dot product using NumPy arrays:", end_time - start_time)

Time taken for element-wise addition using Python lists: 0.09827327728271484
Time taken for element-wise addition using NumPy arrays: 0.004838228225708008

Time taken for element-wise multiplication using Python lists: 0.0777285099029541
Time taken for element-wise multiplication using NumPy arrays: 0.005472421646118164

Time taken for dot product using Python lists: 0.2626047134399414
Time taken for dot product using NumPy arrays: 0.002191781997680664


In [ ]:
import time
import numpy as np

# Generate matrices of size 1000x1000
size = 1000
matrix1 = [[1]*size for _ in range(size)]
matrix2 = [[1]*size for _ in range(size)]

# Matrix multiplication using Python lists
start_time = time.time()
result = [[sum(a*b for a,b in zip(row,col)) for col in zip(*matrix2)] for row in matrix1]
print(f"Time with Python lists: {time.time() - start_time:.4f} seconds")

# Matrix multiplication using NumPy arrays
np_matrix1 = np.array(matrix1)
np_matrix2 = np.array(matrix2)

start_time = time.time()
np.dot(np_matrix1, np_matrix2)
print(f"Time with NumPy arrays: {time.time() - start_time:.4f} seconds")